### ISSUE TITLE
Open3d

### ISSUE THREAD

**Issue by 0xd1ma** [KIT-MRT/mrt_cmake_modules#24]
Hello
I would like to use [open3D](https://github.com/intel-isl/Open3D) in one of my robotics projects under ROS.
Unfortunately, then i add to yaml/cmake.yaml:

```
open3d:
  components: []
  name: Open3D
  include_dirs: [Open3D_INCLUDE_DIRS]
  libraries: [Open3D_LIBRARIES]
  library_dirs: [Open3D_LIBRARY_DIRS]
```
and generate cmake by mrt.

it is possible to build simple code:

```
#include "open3d/Open3D.h"

int main(int argc, char** argv)
{
    using namespace open3d;

    auto sphere = geometry::TriangleMesh::CreateSphere(1.0);
    sphere->ComputeVertexNormals();
    sphere->PaintUniformColor({ 0.0, 1.0, 0.0 });
    visualization::DrawGeometries({ sphere });

    return 0;
}
```

but then i try to add ROS:

```
#include <ros/ros.h>
#include "open3d/Open3D.h"

int main(int argc, char** argv)
{
    using namespace open3d;

    ros::init(argc, argv, "map_loader");

    auto sphere = geometry::TriangleMesh::CreateSphere(1.0);
    sphere->ComputeVertexNormals();
    sphere->PaintUniformColor({ 0.0, 1.0, 0.0 });
    visualization::DrawGeometries({ sphere });

    return 0;
}
```
i have:

`undefined reference to ros::init(int&, char**, std::string const&, unsigned int)`

is it possible to help me with such an issue?
